name: Deploy

on:
  workflow_call:
    inputs:
      platform:
        description: 'Name of the platform'
        required: true
        type: string
      environment:
        description: 'Name of the environment'
        required: true
        type: string
      version:
        description: 'Version of application'
        required: true
        type: string
    secrets:
      acr_name:
        required: true
      kube_config:
        required: true

env:
  PLATFORM:    ${{ inputs.platform }}
  ENVIRONMENT: ${{ inputs.environment }}
  VERSION:     ${{ inputs.version }}
  ACR_NAME:    ${{ secrets.acr_name }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.kube_config }}

      - name: Deploy application to cluster
        run: |
          helm upgrade --install \
            --set acr.name=${ACR_NAME} \
            --set namespace=env-${ENVIRONMENT,,} \
            --set host=${ENVIRONMENT,,}.${PLATFORM,,}.mtapsmartcity.com \
            --set gateway=keycloak-gateway-${ENVIRONMENT,,} \
            --set app.version=${VERSION} \
            ${GITHUB_REPOSITORY##*/}-${ENVIRONMENT,,} ./helm
