on:
  workflow_call:
    inputs:
      registryName:
        required: true
        type: string
      applicationName:
        required: true
        type: string
      applicationVersion:
        required: true
        type: string
    secrets:
      registryUsername:
        required: true
      registryPassword:
        required: true

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      docker-image: ${{ steps.build.outputs.docker-image }}
    steps:
      - name: Login to ${{ inputs.registryName }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registryName }}
          username: ${{ secrets.registryUsername }}
          password: ${{ secrets.registryPassword }}

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.registryName }}/${{ inputs.applicationName }}:${{ inputs.applicationVersion }}
